version: '3.5'
services:
  FlightService:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stage
      MYSQL_USER: Azuz
      MYSQL_PASSWORD: secret2
    volumes:
      - ./dbdata:/var/lib/mysql/
